// Copyright 2016 Yahoo Inc.
// Licensed under the terms of the Apache license. Please see LICENSE.md file distributed with this work for terms.

package main

import (
	"testing"
	"io/ioutil"
	"encoding/json"
	"github.com/ardielle/ardielle-go/rdl"
	"github.com/yahoo/parsec-rdl-gen/utils"
	"bufio"
	"bytes"
	"os"
)
const expectedSampleClientInterface = `//
// This file is generated by test
// WILL NOT be auto-generated if file has already existed.
//
package com.example

import com.example.parsec_generated.ResourceException;
import com.example.parsec_generated.User;
import com.example.parsec_generated.Users;


public interface SampleClient {

    ParsecResponseFuture<User> getUser(int id) throws ResourceException;
    ParsecResponseFuture<User> postUser(User user) throws ResourceException;
    ParsecResponseFuture<User> putUser(int id, User user) throws ResourceException;
    ParsecResponseFuture<User> deleteUser(int id) throws ResourceException;
    ParsecResponseFuture<Users> getUsers(String ids) throws ResourceException;
}
`
func TestGenerateInterface(test *testing.T) {
	data, err := ioutil.ReadFile("../../testdata/sample.json")
	if err != nil {
		test.Error("can not read sample file ")
		os.Exit(1)
	}
	var schema rdl.Schema
	err = json.Unmarshal(data, &schema)
	if err != nil {
		test.Error("unmarshal sample data fail")
		os.Exit(1)
	}

	reg := rdl.NewTypeRegistry(&schema)
	cName := utils.Capitalize(string(schema.Name))

	buf := new (bytes.Buffer)
	writer := bufio.NewWriter(buf)
	gen := &javaClientGenerator{reg, &schema, cName, writer, nil, "test", "", ""}
	gen.processTemplate(javaClientInterfaceTemplate)
	writer.Flush()
	realClientInterface := buf.String()
	if realClientInterface != expectedSampleClientInterface {
		test.Errorf("sample client interface not generated as expected, real: \n%v\n, expected: \n%v\n",
			realClientInterface, expectedSampleClientInterface)
	}
}

/*
 TODO:
 Also need test ClientImpl generator, because ParsecClient template not finally confirmed, need discuss
 with team, so I just skip implClient test at this moment, only test interface generator
*/
